
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kengerona
 */
public class UserDashboard extends javax.swing.JFrame {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/finals";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "root";
    
    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        
        initComponents();
        loadCategoriesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        CategoriesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoriesTable = new javax.swing.JTable();
        CategoriesNameTF = new javax.swing.JTextField();
        CategoriesC = new javax.swing.JButton();
        CategoriesR = new javax.swing.JButton();
        CategoriesU = new javax.swing.JButton();
        CategoriesD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SuppliersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SuppliersTable = new javax.swing.JTable();
        SuppliersC = new javax.swing.JButton();
        SuppliersR = new javax.swing.JButton();
        SuppliersU = new javax.swing.JButton();
        SuppliersD = new javax.swing.JButton();
        SuppliersNameTF = new javax.swing.JTextField();
        SuppliersContTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ItemsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ItemsTable = new javax.swing.JTable();
        ItemsC = new javax.swing.JButton();
        ItemsR = new javax.swing.JButton();
        ItemsU = new javax.swing.JButton();
        ItemsD = new javax.swing.JButton();
        ItemsNameTF = new javax.swing.JTextField();
        ItemsDesTF = new javax.swing.JTextField();
        ItemsCatIDTF = new javax.swing.JComboBox<>();
        ItemsPriceTF = new javax.swing.JTextField();
        ItemsQOHTF = new javax.swing.JTextField();
        ItemsLevTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TransPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TransactionsTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Categories");

        CategoriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "name"
            }
        ));
        jScrollPane1.setViewportView(CategoriesTable);

        CategoriesNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesNameTFActionPerformed(evt);
            }
        });

        CategoriesC.setText("Create");
        CategoriesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesCActionPerformed(evt);
            }
        });

        CategoriesR.setText("Read");
        CategoriesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesRActionPerformed(evt);
            }
        });

        CategoriesU.setText("Update");
        CategoriesU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesUActionPerformed(evt);
            }
        });

        CategoriesD.setText("Delete");
        CategoriesD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesDActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        javax.swing.GroupLayout CategoriesPanelLayout = new javax.swing.GroupLayout(CategoriesPanel);
        CategoriesPanel.setLayout(CategoriesPanelLayout);
        CategoriesPanelLayout.setHorizontalGroup(
            CategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriesPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(CategoriesPanelLayout.createSequentialGroup()
                .addGroup(CategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoriesPanelLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(CategoriesC)
                        .addGap(18, 18, 18)
                        .addGroup(CategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CategoriesPanelLayout.createSequentialGroup()
                                .addComponent(CategoriesR)
                                .addGap(28, 28, 28)
                                .addComponent(CategoriesU)
                                .addGap(18, 18, 18)
                                .addComponent(CategoriesD))
                            .addComponent(CategoriesNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CategoriesPanelLayout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jLabel5)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        CategoriesPanelLayout.setVerticalGroup(
            CategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriesPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CategoriesNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(CategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriesC)
                    .addComponent(CategoriesR)
                    .addComponent(CategoriesU)
                    .addComponent(CategoriesD))
                .addGap(51, 51, 51))
        );

        jLayeredPane1.add(CategoriesPanel, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Suppliers");

        SuppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact"
            }
        ));
        jScrollPane2.setViewportView(SuppliersTable);

        SuppliersC.setText("Create");
        SuppliersC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersCActionPerformed(evt);
            }
        });

        SuppliersR.setText("Read");
        SuppliersR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersRActionPerformed(evt);
            }
        });

        SuppliersU.setText("Update");
        SuppliersU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersUActionPerformed(evt);
            }
        });

        SuppliersD.setText("Delete");
        SuppliersD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersDActionPerformed(evt);
            }
        });

        SuppliersNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersNameTFActionPerformed(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("Contact Info");

        javax.swing.GroupLayout SuppliersPanelLayout = new javax.swing.GroupLayout(SuppliersPanel);
        SuppliersPanel.setLayout(SuppliersPanelLayout);
        SuppliersPanelLayout.setHorizontalGroup(
            SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuppliersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(SuppliersPanelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                                .addComponent(SuppliersC)
                                .addGap(18, 18, 18)
                                .addComponent(SuppliersR))
                            .addComponent(SuppliersNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                                .addComponent(SuppliersU)
                                .addGap(18, 18, 18)
                                .addComponent(SuppliersD))
                            .addComponent(SuppliersContTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel6)
                .addGap(144, 144, 144)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuppliersPanelLayout.setVerticalGroup(
            SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuppliersNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuppliersContTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(SuppliersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuppliersC)
                    .addComponent(SuppliersR)
                    .addComponent(SuppliersU)
                    .addComponent(SuppliersD))
                .addGap(48, 48, 48))
        );

        jLayeredPane1.add(SuppliersPanel, "card3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Items");

        ItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "name", "description", "category id", "price", "quantity on hand", "reorder level"
            }
        ));
        jScrollPane3.setViewportView(ItemsTable);

        ItemsC.setText("Create");
        ItemsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsCActionPerformed(evt);
            }
        });

        ItemsR.setText("Read");
        ItemsR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsRActionPerformed(evt);
            }
        });

        ItemsU.setText("Update");
        ItemsU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsUActionPerformed(evt);
            }
        });

        ItemsD.setText("Delete");
        ItemsD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsDActionPerformed(evt);
            }
        });

        ItemsDesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsDesTFActionPerformed(evt);
            }
        });

        jLabel8.setText("Name");

        jLabel9.setText("Description");

        jLabel10.setText("Category");

        jLabel11.setText("Price");

        jLabel12.setText("Stock");

        jLabel13.setText("ReorderLvl");

        javax.swing.GroupLayout ItemsPanelLayout = new javax.swing.GroupLayout(ItemsPanel);
        ItemsPanel.setLayout(ItemsPanelLayout);
        ItemsPanelLayout.setHorizontalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(ItemsC)
                .addGap(18, 18, 18)
                .addComponent(ItemsR)
                .addGap(24, 24, 24)
                .addComponent(ItemsU)
                .addGap(18, 18, 18)
                .addComponent(ItemsD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(ItemsNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)))
                .addGap(89, 89, 89)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemsDesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)))
                .addGap(78, 78, 78)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addComponent(ItemsCatIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(ItemsPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(ItemsQOHTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel11)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemsLevTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ItemsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)))
                .addGap(44, 44, 44))
        );
        ItemsPanelLayout.setVerticalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemsNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsDesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsCatIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsQOHTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsLevTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemsC)
                    .addComponent(ItemsR)
                    .addComponent(ItemsU)
                    .addComponent(ItemsD))
                .addGap(46, 46, 46))
        );

        jLayeredPane1.add(ItemsPanel, "card4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Transactions");

        TransactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Date", "Quantity", "Type", "Notes"
            }
        ));
        jScrollPane4.setViewportView(TransactionsTable);

        javax.swing.GroupLayout TransPanelLayout = new javax.swing.GroupLayout(TransPanel);
        TransPanel.setLayout(TransPanelLayout);
        TransPanelLayout.setHorizontalGroup(
            TransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 807, Short.MAX_VALUE))
            .addGroup(TransPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        TransPanelLayout.setVerticalGroup(
            TransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 154, Short.MAX_VALUE))
        );

        jLayeredPane1.add(TransPanel, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Categories");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Suppliers");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Items");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Transactions");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("PurchaseOrders");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    CategoriesPanel.setVisible(true);
    SuppliersPanel.setVisible(false);
    ItemsPanel.setVisible(false);
    TransPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    CategoriesPanel.setVisible(false);
    SuppliersPanel.setVisible(true);
    ItemsPanel.setVisible(false);
    TransPanel.setVisible(false);
    loadSuppliersTable();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    CategoriesPanel.setVisible(false);
    SuppliersPanel.setVisible(false);
    ItemsPanel.setVisible(true);
    TransPanel.setVisible(false);
    loadItemsTable();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    CategoriesPanel.setVisible(false);
    SuppliersPanel.setVisible(false);
    ItemsPanel.setVisible(false);
    TransPanel.setVisible(true);
    loadTransactionsTable();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void CategoriesNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriesNameTFActionPerformed

    private void CategoriesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesCActionPerformed
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
        String query = "INSERT INTO Categories (category_name) VALUES (?)";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, CategoriesNameTF.getText());
                pstmt.executeUpdate();
                } catch (SQLException e) {
            e.printStackTrace();
        }
        
        loadCategoriesTable();
    }//GEN-LAST:event_CategoriesCActionPerformed

    private void CategoriesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesRActionPerformed
        int selectedrow  = CategoriesTable.getSelectedRow();
        int columnIndex = 0;
        Object id = CategoriesTable.getValueAt(selectedrow, columnIndex);
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");

            Statement statement;
            statement = conn.createStatement();
            String query = "select * from Categories where category_id = " + id;
            ResultSet sqlresult = statement.executeQuery(query);
            int Cid = 0;
            String name = "";
            
            while(sqlresult.next()){
                Cid = Integer.parseInt(sqlresult.getString("category_id"));
                name = sqlresult.getString("category_name");
            }
            String read = String.format("Category id: %d\nCategory Name: %s", Cid, name);
            JOptionPane.showMessageDialog(null, read);
           

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_CategoriesRActionPerformed

    private void CategoriesUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesUActionPerformed
        int selectedrow  = CategoriesTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = CategoriesTable.getValueAt(selectedrow, columnIndex);    
        int id = Integer.parseInt((String) idid);
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            String query = "UPDATE Categories SET category_name = ? WHERE category_id = ?";
                    PreparedStatement pstmt = conn.prepareStatement(query);
                    pstmt.setString(1, CategoriesNameTF.getText().toString());
                    pstmt.setInt(2, id);
                    pstmt.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        loadCategoriesTable();
    }//GEN-LAST:event_CategoriesUActionPerformed

    private void CategoriesDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesDActionPerformed
        int selectedrow  = CategoriesTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = CategoriesTable.getValueAt(selectedrow, columnIndex);    
        int id = Integer.parseInt((String) idid);
        
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                String query = query = "DELETE FROM Categories WHERE category_id = ?";
                
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            loadCategoriesTable();
    }//GEN-LAST:event_CategoriesDActionPerformed

    private void SuppliersCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersCActionPerformed
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
        String query = "INSERT INTO Suppliers (supplier_name, contact_info) VALUES (?,?)";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, SuppliersNameTF.getText());
                pstmt.setString(2, SuppliersContTF.getText());
                pstmt.executeUpdate();
                } catch (SQLException e) {
            e.printStackTrace();
        }
        
        loadSuppliersTable();
    }//GEN-LAST:event_SuppliersCActionPerformed

    private void SuppliersRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersRActionPerformed
       int selectedrow  = SuppliersTable.getSelectedRow();
        int columnIndex = 0;
        Object id = SuppliersTable.getValueAt(selectedrow, columnIndex);
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");

            Statement statement;
            statement = conn.createStatement();
            String query = "select * from Suppliers where supplier_id = " + id;
            ResultSet sqlresult = statement.executeQuery(query);
            int Cid = 0;
            String name = "";
            String contact = "";
            
            while(sqlresult.next()){
                Cid = Integer.parseInt(sqlresult.getString("supplier_id"));
                name = sqlresult.getString("supplier_name");
                contact = sqlresult.getString("contact_info");
                
            }
            String read = String.format("Category id: %d\nCategory Name: %s\nContact Info: %s", Cid, name, contact);
            JOptionPane.showMessageDialog(null, read);
           

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SuppliersRActionPerformed

    private void SuppliersUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersUActionPerformed
        int selectedrow  = SuppliersTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = SuppliersTable.getValueAt(selectedrow, columnIndex);    
        int id = Integer.parseInt((String) idid);
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            String query = "UPDATE Suppliers SET supplier_name = ?, contact_info = ? WHERE supplier_id = ?";
                    PreparedStatement pstmt = conn.prepareStatement(query);
                    pstmt.setString(1, SuppliersNameTF.getText().toString());
                    pstmt.setString(2, SuppliersContTF.getText().toString());
                    pstmt.setInt(3, id);
                    pstmt.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        loadSuppliersTable();
    }//GEN-LAST:event_SuppliersUActionPerformed

    private void SuppliersDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersDActionPerformed
       int selectedrow  = SuppliersTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = SuppliersTable.getValueAt(selectedrow, columnIndex);    
        int id = Integer.parseInt((String) idid);
        
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                String query = query = "DELETE FROM Suppliers WHERE supplier_id = ?";
                
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setInt(1, id);
                pstmt.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            loadSuppliersTable();
    }//GEN-LAST:event_SuppliersDActionPerformed

    private void SuppliersNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuppliersNameTFActionPerformed

    private void ItemsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsCActionPerformed
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
        String query = "INSERT INTO Items (item_name, description, category_id, unit_price, quantity_on_hand, reorder_level) VALUES (?,?,?,?,?,?)";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, ItemsNameTF.getText());
                pstmt.setString(2, ItemsDesTF.getText());
                pstmt.setString(3, ItemsCatIDTF.getSelectedItem().toString());
                pstmt.setString(4, ItemsPriceTF.getText());
                pstmt.setString(5, ItemsQOHTF.getText());
                pstmt.setString(6, ItemsLevTF.getText());
                
                pstmt.executeUpdate();
                } catch (SQLException e) {
            e.printStackTrace();
        }
        
        loadItemsTable();
    }//GEN-LAST:event_ItemsCActionPerformed

    private void ItemsRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsRActionPerformed
        int selectedrow  = ItemsTable.getSelectedRow();
        int columnIndex = 0;
        Object id = ItemsTable.getValueAt(selectedrow, columnIndex);
        System.out.println(id);
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");

            Statement statement;
            statement = conn.createStatement();
            String query = "select * from Items where item_name = " + id;
            ResultSet sqlresult = statement.executeQuery(query);
            int Cid = 0;
            String name = "";
            String des = "";
            int catid = 0;
            double price = 0;
            int stock = 0;
            int reorderlvl = 0;
            
            while(sqlresult.next()){
                Cid = Integer.parseInt(sqlresult.getString("item_id"));
                name = sqlresult.getString("item_name");
                des = sqlresult.getString("description");
                catid = Integer.parseInt(sqlresult.getString("category_id"));
                price = Double.parseDouble(sqlresult.getString("unit_price"));
                stock = Integer.parseInt(sqlresult.getString("quantity_on_hand"));
                reorderlvl = Integer.parseInt(sqlresult.getString("reorder_level"));
            }
            String read = String.format("Item id: %d\nItem Name: %s\nItem Description: %s\nCategory: %d\nPrice: %.2f\nStock: %d\nReorder Level: %d", Cid, name, des,catid,price,stock,reorderlvl);
            JOptionPane.showMessageDialog(null, read);
           

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ItemsRActionPerformed

    private void ItemsUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsUActionPerformed
        int selectedrow  = ItemsTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = ItemsTable.getValueAt(selectedrow, columnIndex);    
        String id = (String) idid;
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            String query = "UPDATE items SET item_name = ?, description = ?, category_id = ?, unit_price = ?, quantity_on_hand = ?, reorder_level = ? WHERE item_name = ?";
                    PreparedStatement pstmt = conn.prepareStatement(query);
                    pstmt.setString(1, ItemsNameTF.getText().toString());
                    pstmt.setString(2, ItemsDesTF.getText().toString());
                    pstmt.setInt(3, Integer.parseInt((String)ItemsCatIDTF.getSelectedItem()));
                    pstmt.setDouble(4, Double.parseDouble(ItemsPriceTF.getText().toString()));
                    pstmt.setInt(5, Integer.parseInt((ItemsQOHTF.getText().toString())));
                    pstmt.setInt(6, Integer.parseInt((ItemsLevTF.getText().toString())));
                    pstmt.setString(7, id);
                    pstmt.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        ItemsCatIDTF.removeAllItems();
        loadItemsTable();
    }//GEN-LAST:event_ItemsUActionPerformed

    private void ItemsDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsDActionPerformed
        int selectedrow  = ItemsTable.getSelectedRow();
        int columnIndex = 0;
        Object idid = ItemsTable.getValueAt(selectedrow, columnIndex);    
        String id = (String) idid;
        
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                String query = query = "DELETE FROM Items WHERE item_name = ?";
                
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, id);
                pstmt.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            ItemsCatIDTF.removeAllItems();
            loadItemsTable();
    }//GEN-LAST:event_ItemsDActionPerformed

    private void ItemsDesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsDesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemsDesTFActionPerformed
    
    private void fetchAndDisplayData(JTable table, String tableName) {
        DefaultTableModel model = new DefaultTableModel();
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String query = "SELECT * FROM " + tableName;
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Set table columns based on result set
            Vector<String> columns = new Vector<>();
            for (int i = 1; i <= columnCount; i++) {
                columns.add(metaData.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            // Fill table data
            Vector<Vector<Object>> data = new Vector<>();
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    row.add(rs.getObject(i));
                }
                data.add(row);
            }

            model.setDataVector(data, columns);
            table.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public static void loadCategoriesTable(){
        try(Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            
            Statement statement;
            statement = conn.createStatement();
            ResultSet resultset;
            resultset = statement.executeQuery("SELECT * FROM Categories");
            
            
            DefaultTableModel model = new DefaultTableModel(new String[] {"Category ID", "Name"}, 0);
            
            
            CategoriesTable.setModel(model);

            
            while(resultset.next()){
                model.addRow(new Object[] {resultset.getString(1), resultset.getString(2)});
                
            }
        }catch(Exception e){
            
        }
    }
    
    public static void loadSuppliersTable(){
        try(Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            
            Statement statement;
            statement = conn.createStatement();
            ResultSet resultset;
            resultset = statement.executeQuery("SELECT * FROM Suppliers");
            
            
            DefaultTableModel model = new DefaultTableModel(new String[] {"Supplier ID", "Name", "Contact Info"}, 0);
            
            
            SuppliersTable.setModel(model);

            
            while(resultset.next()){
                model.addRow(new Object[] {resultset.getString(1), resultset.getString(2), resultset.getString(3)});
                
            }
        }catch(Exception e){
            
        }
    }
    
    public static void loadItemsTable(){
        try(Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            
            Statement statement;
            statement = conn.createStatement();
            ResultSet resultset;
            resultset = statement.executeQuery("SELECT * FROM Items");
            
            
            DefaultTableModel model = new DefaultTableModel(new String[] {"Name", "Description", "Category", "Price", "Quantity on Hand", "Reorder Level"}, 0);
            ItemsTable.setModel(model);

            
            while(resultset.next()){
                model.addRow(new Object[] {resultset.getString(2), resultset.getString(3), resultset.getString(4), resultset.getString(5), resultset.getString(6), resultset.getString(7)});
            }
            
            resultset = statement.executeQuery("SELECT * FROM Categories");
            while(resultset.next()){
                ItemsCatIDTF.addItem(resultset.getString(1));
            }
            
        }catch(Exception e){
            
        }
    }
    public static void loadTransactionsTable(){
        try(Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)){
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            
            Statement statement;
            statement = conn.createStatement();
            ResultSet resultset;
            resultset = statement.executeQuery("SELECT * FROM Transactions");
            
            
            DefaultTableModel model = new DefaultTableModel(new String[] {"Item ID", "Date", "Quantity", "Type", "Notes"}, 0);
            TransactionsTable.setModel(model);

            
            while(resultset.next()){
                model.addRow(new Object[] {resultset.getString(2), resultset.getString(3), resultset.getString(4), resultset.getString(5), resultset.getString(6)});
            }
            
            
        }catch(Exception e){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriesC;
    private javax.swing.JButton CategoriesD;
    private javax.swing.JTextField CategoriesNameTF;
    private javax.swing.JPanel CategoriesPanel;
    private javax.swing.JButton CategoriesR;
    private static javax.swing.JTable CategoriesTable;
    private javax.swing.JButton CategoriesU;
    private javax.swing.JButton ItemsC;
    private static javax.swing.JComboBox<String> ItemsCatIDTF;
    private javax.swing.JButton ItemsD;
    private javax.swing.JTextField ItemsDesTF;
    private javax.swing.JTextField ItemsLevTF;
    private javax.swing.JTextField ItemsNameTF;
    private javax.swing.JPanel ItemsPanel;
    private javax.swing.JTextField ItemsPriceTF;
    private javax.swing.JTextField ItemsQOHTF;
    private javax.swing.JButton ItemsR;
    private static javax.swing.JTable ItemsTable;
    private javax.swing.JButton ItemsU;
    private javax.swing.JButton SuppliersC;
    private javax.swing.JTextField SuppliersContTF;
    private javax.swing.JButton SuppliersD;
    private javax.swing.JTextField SuppliersNameTF;
    private javax.swing.JPanel SuppliersPanel;
    private javax.swing.JButton SuppliersR;
    private static javax.swing.JTable SuppliersTable;
    private javax.swing.JButton SuppliersU;
    private javax.swing.JPanel TransPanel;
    private static javax.swing.JTable TransactionsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
